name: build
on: workflow_dispatch
  
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Create archive
        uses: ksm2/archive-action@v1
        with: 
          format: "tar"
          name: aquaia_archive
          path: /docker/build/aquaia_archive.tar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/build/Dockerfile
          tags: aquaia/aquaia:latest
          push: true
          load: true
      - name: Save Docker image as artifact
        run: docker save aquia/aquaia:latest -o aquaia_latest.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aquaia_docker_image
          path: aquaia_image.tar
          retention-days: 3